### PR TITLE
add savings bonuses

### PR DESCRIPTION
**Pull request by sofiathoren**

### CODE REVIEW

**Review by csioa — APPROVED** [review]
LGTM

**Review by csioa — CHANGES_REQUESTED** [review]
Have you run terraform apply?

**Review by csioa — CHANGES_REQUESTED** [review]
Have you run terraform apply?

**Comment by sofiathoren** [comment]
> Have you run terraform apply?

yes it created a table called savings_bonuses_raw, but should it not also create a savings_bonuses?

**Review by csioa — APPROVED** [review]
LGTM - I could not see the table before. No other changes needed

**Pull request merged**
